[package]
name = "genai-tools-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
schemars = "0.8.21"
serde_json = "1.0.122"
syn = { version = "2.0.72", features = ["full"] }
